import type { Bounty } from '@/types/bounty'

export const MOCK_BOUNTIES: Bounty[] = [
  {
    id: '1',
    title: 'Fix XDR decoding bug in transaction parsing',
    description:
      'The XDR decoder throws an uncaught exception on malformed input instead of returning a structured error. Needs proper error handling and unit tests.',
    repoUrl: 'https://github.com/stellar/js-stellar-sdk',
    issueUrl: 'https://github.com/stellar/js-stellar-sdk/issues/842',
    issueNumber: 842,
    repoName: 'stellar/js-stellar-sdk',
    organization: 'Stellar Development Foundation',
    status: 'open',
    reward: 500,
    token: 'USDC',
    tags: ['bug', 'typescript', 'xdr', 'good-first-issue'],
    postedBy: 'GABCDEFGHIJKLMNOPQRSTUVWXYZ12345678901234567890ABCD',
    claimedBy: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    milestonesTotal: 3,
    milestonesCompleted: 0,
  },
  {
    id: '2',
    title: 'Add Soroban smart contract integration tests',
    description:
      'We need a full integration test suite for the escrow contract covering deposit, claim, dispute, and refund flows.',
    repoUrl: 'https://github.com/stellar/soroban-examples',
    issueUrl: 'https://github.com/stellar/soroban-examples/issues/210',
    issueNumber: 210,
    repoName: 'stellar/soroban-examples',
    organization: 'Stellar Development Foundation',
    status: 'claimed',
    reward: 1500,
    token: 'XLM',
    tags: ['soroban', 'testing', 'rust', 'smart-contract'],
    postedBy: 'GXYZ1234ABCD5678EFGH9012IJKL3456MNOP7890QRST1234UVWX',
    claimedBy: 'GCLAIMR1234ABCD5678EFGH9012IJKL3456MNOP7890QRST1234',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    milestonesTotal: 4,
    milestonesCompleted: 1,
  },
  {
    id: '3',
    title: 'Implement path payment strict send UI',
    description:
      'Build a UI component for path payment strict send transactions in the Stellar wallet reference implementation.',
    repoUrl: 'https://github.com/stellar/freighter',
    issueUrl: 'https://github.com/stellar/freighter/issues/567',
    issueNumber: 567,
    repoName: 'stellar/freighter',
    organization: 'Stellar Development Foundation',
    status: 'in_review',
    reward: 750,
    token: 'USDC',
    tags: ['frontend', 'react', 'payments', 'ux'],
    postedBy: 'GREVIEW1234ABCD5678EFGH9012IJKL3456MNOP7890QRST123',
    claimedBy: 'GSUBMIT1234ABCD5678EFGH9012IJKL3456MNOP7890QRST123',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: null,
    milestonesTotal: 2,
    milestonesCompleted: 2,
  },
  {
    id: '4',
    title: 'Document Horizon API rate limiting behaviour',
    description:
      'Write clear documentation on Horizon rate limits, retry strategies, and how to handle 429 responses.',
    repoUrl: 'https://github.com/stellar/stellar-docs',
    issueUrl: 'https://github.com/stellar/stellar-docs/issues/331',
    issueNumber: 331,
    repoName: 'stellar/stellar-docs',
    organization: 'Stellar Development Foundation',
    status: 'completed',
    reward: 200,
    token: 'XLM',
    tags: ['docs', 'horizon', 'api'],
    postedBy: 'GDOCS1234ABCD5678EFGH9012IJKL3456MNOP7890QRST1234UV',
    claimedBy: 'GWRITER1234ABCD5678EFGH9012IJKL3456MNOP7890QRST12',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: null,
    milestonesTotal: 1,
    milestonesCompleted: 1,
  },
  {
    id: '5',
    title: 'Fix memory leak in Stellar Base keypair generation',
    description:
      'Profiling shows a memory leak when generating large batches of keypairs. Root cause traced to event listener not being cleaned up.',
    repoUrl: 'https://github.com/stellar/stellar-base',
    issueUrl: 'https://github.com/stellar/stellar-base/issues/174',
    issueNumber: 174,
    repoName: 'stellar/stellar-base',
    organization: 'Stellar Development Foundation',
    status: 'disputed',
    reward: 300,
    token: 'USDC',
    tags: ['bug', 'performance', 'memory', 'javascript'],
    postedBy: 'GDISPUTE1234ABCD5678EFGH9012IJKL3456MNOP7890QRST1',
    claimedBy: 'GCLAIM2134ABCD5678EFGH9012IJKL3456MNOP7890QRST123',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    milestonesTotal: 2,
    milestonesCompleted: 1,
  },
]
